location-rg = "uksouth"
# DOCKER_REGISTRY_SERVER_PASSWORD =    #__DOCKER_REGISTRY_SERVER_PASSWORD__
# DOCKER_REGISTRY_SERVER_URL =       #__DOCKER_REGISTRY_SERVER_URL__
# DOCKER_REGISTRY_SERVER_USERNAME =      # __DOCKER_REGISTRY_SERVER_USERNAME__

docker_image_tag =__DOCKER_IMAGE_TAG__
docker_image = __DOCKER_IMAGE__