name: build and deploy two tier application to azure app service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - none

env:
  # DOCKER_IMAGE: ""
  DOCKER_IMAGE_NAME: aquilacms
  LOCATION: westeurope
  INFRA_RESOURCE_GROUP: tfstate-resourcegroup
  TF_STATE_STORAGE_ACCOUNT_NAME: tfstatestorage10275789
  TF_STATE_CONTAINER_NAME: tfstate
  TF_STATE_FILE_NAME: tfstate
  TF_STATE_ACCESS_KEY: ""
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: destroy terraform config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: docker_image.txt  
            
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image-tag
          path: docker_image_tag.txt

      - name: Set DOCKER_IMAGE environment variable
        run: |
              echo "DOCKER_IMAGE=$(cat docker_image.txt/docker_image.txt)" >> $GITHUB_ENV

              echo "DOCKER_IMAGE_TAG=$(cat docker_image_tag.txt/docker_image_tag.txt)" >> $GITHUB_ENV  
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Replace Variables in terraform.tfvars
        uses: datamonsters/replace-action@v2
        with:
         files: infrastructure/azurewebapp.tf
         replacements: |
          __DOCKER_IMAGE_TAG__ = "${{ env.DOCKER_IMAGE_TAG }}", __DOCKER_IMAGE__ = "${{ env.DOCKER_IMAGE }}"

      - name: Terraform Init (Azure Backend)
        id: init
        run: terraform init 
          -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME"
          -backend-config="container_name=$TF_STATE_CONTAINER_NAME"
          -backend-config="access_key=$TF_STATE_ACCESS_KEY" 
          -backend-config="key=$TF_STATE_FILE_NAME"
        working-directory: infrastructure

      - name: Terraform destroy 
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform destroy -auto-approve
        working-directory: infrastructure
        continue-on-error: true

